### ISSUE TITLE
Indice fragilité numérique

### ISSUE THREAD

**Issue by christmknd** [jules3198/green-it#8]

**Comment by christmknd** [comment]
Etapes de l'algo
1. Injection des données brutes dans la BDD
2. Algo récupère les données de la BDD 
3.  Algo trie fait les calculs et envoie au front 
4. Front affiche les resultats

**Comment by maxd935** [comment]
Récupération de l'indice de fragilité par commune, par département, par région.
Récupération des 4 indicateurs par commune.
